<?php

namespace Dbronczyk\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnarieRepository extends EntityRepository
{
}
